import {_electron as electron,expect} from '@playwright/test';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {zipSync,strToU8} from 'fflate';
const directory=await mkdtemp(path.join(tmpdir(),'characters-test-')),env={...process.env,COMPANION_TEST_DATA:directory};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({args:process.env.COMPANION_EXECUTABLE?[]:['.'],executablePath:process.env.COMPANION_EXECUTABLE,env});
try{
 let pet=await app.firstWindow();await pet.waitForFunction(()=>!!window.companion);await pet.evaluate(()=>window.companion.action('open','settings'));const panel=app.windows().find(p=>p.url().includes('view=panel'));await panel.waitForSelector('#guideDone');await panel.locator('#guideDone').click();pet=app.windows().find(p=>p.url().includes('view=pet'));
 const choose=async(files)=>app.evaluate(({dialog},files)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:files});},files);
 const initial=await panel.evaluate(()=>window.companion.state());const library=await panel.evaluate(()=>window.companion.memory());assert(library.characters.some(p=>p.id==='builtin-momo'));assert(library.characters.length>=2);
 await panel.evaluate(()=>window.companion.action('chat','我的原角色聊天'));await expect.poll(()=>panel.evaluate(async()=>!(await window.companion.state()).busy)).toBe(true);await panel.evaluate(()=>window.companion.action('fact-save',{content:'喜欢蓝色'}));
 const oldHistory=await panel.evaluate(()=>window.companion.history());assert(oldHistory.length>=2);const oldSession=(await panel.evaluate(()=>window.companion.state())).sessionId;
 await choose([path.resolve('assets/characters/momo/idle.png')]);assert.equal(await panel.evaluate(()=>window.companion.action('image-import')),true);let state=await panel.evaluate(()=>window.companion.state());assert.equal(state.settings.characterId,initial.settings.characterId);assert.equal(state.sessionId,oldSession);assert.equal((await panel.evaluate(()=>window.companion.history())).length,oldHistory.length);assert.equal((await panel.evaluate(()=>window.companion.memory())).facts.length,1);
 const originalImage=state.character.frames.idle[0],broken=path.join(directory,'broken.png');await writeFile(broken,(await readFile('assets/default-character/idle.png')).subarray(0,24));await choose([broken]);const invalid=await panel.evaluate(()=>window.companion.action('image-import'));assert(invalid.error.includes('图片无法读取'));assert.equal((await panel.evaluate(()=>window.companion.state())).character.frames.idle[0],originalImage);
 await choose([path.resolve('assets/default-character/walk-2.png'),path.resolve('assets/default-character/walk-1.png')]);assert.equal(await panel.evaluate(()=>window.companion.action('action-import',{action:'walk',frameMs:100})),true);state=await panel.evaluate(()=>window.companion.state());assert.equal(state.character.frames.walk.length,2);assert.equal(state.character.frameMs.walk,100);await panel.evaluate(()=>window.companion.action('action-preview','walk'));await expect(pet.locator('#petImage')).toHaveAttribute('data-action','walk');
 await panel.evaluate(()=>window.companion.action('character-select','builtin-momo'));await expect.poll(()=>pet.locator('#petImage').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 await panel.locator('#manageCharacters').click();await expect(panel.locator('.characterTile')).toHaveCount(library.characters.length);await panel.locator('#manageActions').click();await panel.waitForSelector('#actionPreviewImage');assert.equal(await panel.locator('#actionName option').count(),5);await panel.locator('#editorCancel').click();
 await panel.evaluate(()=>window.companion.action('character-select', 'default-xiaoqi'));assert.equal((await panel.evaluate(()=>window.companion.state())).sessionId,oldSession);assert.equal((await panel.evaluate(()=>window.companion.history())).length,oldHistory.length);
 await choose([path.resolve('assets/characters/momo/idle.png')]);assert.equal(await panel.evaluate(()=>window.companion.action('image-import',{newCharacter:true})),true);const fresh=(await panel.evaluate(()=>window.companion.state())).settings.characterId;assert.notEqual(fresh,initial.settings.characterId);assert.equal((await panel.evaluate(()=>window.companion.history())).length,0);
 const zip=path.join(directory,'sample.zip'),bytes=await readFile('assets/default-character/idle.png');await writeFile(zip,zipSync({'character.json':strToU8(JSON.stringify({schema_version:1,id:'example',name:'动作包示例',persona_text:'耐心陪伴',visual_type:'frames',asset_paths:{idle:['idle.png'],click:['idle.png']},supported_actions:['idle','click'],fallback_action:'idle',frame_ms:{idle:120},license:'MIT',source:'测试文件'})),'idle.png':bytes}));await choose([zip]);assert.equal(await panel.evaluate(()=>window.companion.action('character-import')),true);assert.equal((await panel.evaluate(()=>window.companion.state())).settings.name,'动作包示例');
 await panel.evaluate(()=>window.companion.action('character-select','default-xiaoqi'));assert.equal((await panel.evaluate(()=>window.companion.memory())).facts.length,1);assert.equal((await panel.evaluate(()=>window.companion.history())).length,oldHistory.length);
 console.log('PASS: Windows original built-in roles, current appearance preserves identity/history/memory, PNG action sequence import and preview, independent new role, role switching restores session, actual ZIP package import.');
}finally{await app.close();}
