import { _electron as electron,expect } from '@playwright/test';
import { mkdtemp, mkdir,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const env={...process.env,COMPANION_TEST_DATA:await mkdtemp(path.join(tmpdir(),'companion-test-'))};delete env.ELECTRON_RUN_AS_NODE;
const application=await electron.launch({args:process.env.COMPANION_EXECUTABLE?[]:['.'],executablePath:process.env.COMPANION_EXECUTABLE,env,timeout:30000});
try {
  const page=await application.firstWindow();await page.waitForFunction(()=>!!window.companion);
  await page.evaluate(()=>window.companion.action('open','chat'));
  const panel=application.windows().find(p=>p.url().includes('view=panel'));
  await panel.waitForSelector('#messageInput');
  await panel.waitForSelector('#guideDone');await panel.locator('#guideDone').click();
  const errors=[];panel.on('pageerror',e=>errors.push(e.message));
  await page.evaluate(()=>window.companion.action('open','settings'));await expect(panel.locator('#pageTitle')).toHaveText('伙伴设置');
  await application.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=panel')).hide();globalThis.__companionTest.tray.emit('double-click');});
  await expect(panel.locator('#pageTitle')).toHaveText('聊一聊');assert(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=panel')).isVisible()));
  const petFeedback=application.windows().find(p=>p.url().includes('view=pet')),speech=application.windows().find(p=>p.url().includes('view=bubble'));
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=panel')).hide());
  await petFeedback.locator('#petControls').evaluate(el=>el.style.opacity='1');await petFeedback.locator('#petQuiet').click();
  await expect(petFeedback.locator('#petQuiet')).toHaveText('醒');await expect(petFeedback.locator('#petQuiet')).toHaveAttribute('aria-pressed','true');await expect(petFeedback.locator('#petStatus')).toBeVisible();await expect(speech.locator('#bubble')).toContainText('已开启勿扰');
  await petFeedback.locator('#petHide').click();const feedbackRestore=application.windows().find(p=>p.url().includes('view=restore'));await expect(feedbackRestore.locator('#restoreAvatar')).toBeVisible();assert.equal(await feedbackRestore.locator('#restorePet').innerText(),'☾');await expect(feedbackRestore.locator('.restoreQuiet')).toBeVisible();await feedbackRestore.locator('#restorePet').click();
  await petFeedback.locator('#petQuiet').click();await expect(petFeedback.locator('#petQuiet')).toHaveText('静');await expect(petFeedback.locator('#petStatus')).toBeHidden();await expect(speech.locator('#bubble')).toContainText('已退出勿扰');
  for(const side of ['left','right']){
    await application.evaluate(({BrowserWindow,screen},side)=>{const pet=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=pet')),area=screen.getPrimaryDisplay().workArea,b=pet.getBounds();pet.setPosition(side==='left'?area.x:area.x+area.width-b.width,area.y+100);},side);
    await new Promise(r=>setTimeout(r,1250));await page.evaluate(()=>window.companion.action('open','quick'));
    const geometry=await application.evaluate(({BrowserWindow,screen})=>{const all=BrowserWindow.getAllWindows(),pet=all.find(w=>w.webContents.getURL().includes('view=pet')).getBounds(),quick=all.find(w=>w.webContents.getURL().includes('view=quick')).getBounds();return {pet,quick,area:screen.getDisplayMatching(pet).workArea};});
    assert(geometry.quick.x>=geometry.area.x);assert(geometry.quick.x+geometry.quick.width<=geometry.area.x+geometry.area.width);assert(side==='left'?geometry.quick.x>=geometry.pet.x+geometry.pet.width:geometry.quick.x+geometry.quick.width<=geometry.pet.x);
  }
  await page.evaluate(()=>window.companion.action('open','chat'));
  const initialSession=(await panel.evaluate(()=>window.companion.state())).sessionId;
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=panel')).close());
  await page.evaluate(()=>window.companion.action('open','chat'));assert.equal((await panel.evaluate(()=>window.companion.state())).sessionId,initialSession);
  for(const scale of [1.6,0.6,1.3,0.5,2,1]){
    await panel.evaluate(scale=>window.companion.action('resize',scale),scale);
    const bounds=await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=pet')).getBounds());
    assert.equal(bounds.width,Math.round(310*scale));assert.equal(bounds.height,Math.round(270*scale));
    const petPage=application.windows().find(p=>p.url().includes('view=pet'));await expect.poll(()=>petPage.evaluate(()=>innerWidth)).toBe(bounds.width);
  }
  await panel.evaluate(()=>window.companion.action('settings',{name:'小樱',firstName:true}));
  const quickPage=application.windows().find(p=>p.url().includes('view=quick'));await expect(quickPage.locator('#quickName')).toHaveText('小樱');await expect(panel.locator('#brandName')).toHaveText('小樱');
  assert.equal(await panel.locator('.compose #learnStart').count(),0);assert.equal(await panel.locator('.chatTop #learnStart').count(),1);
  const textFile=path.join(env.COMPANION_TEST_DATA,'whole.txt');await writeFile(textFile,'文件全文'.repeat(2000)+'全文末尾标记','utf8');
  await application.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},textFile);
  const upload=panel.evaluate(()=>window.companion.action('document-import'));await panel.waitForSelector('#confirmAccept');await panel.locator('#confirmAccept').click();assert(!(await upload)?.error);
  const document=(await panel.evaluate(()=>window.companion.state())).context;assert(document.full_document);assert(document.content_excerpt.endsWith('全文末尾标记'));assert(document.content_excerpt.length>4000);
  await panel.locator('#sourcePreview').click();assert.equal(await panel.locator('#pdfPage').count(),0);await panel.locator('#sourceDone').click();await panel.locator('#sourceRemove').click();
  const avatarFile=path.resolve('assets/default-character/idle.png');await application.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},avatarFile);
  await panel.locator('#changeAvatar').click();await expect.poll(()=>panel.evaluate(async()=>(await window.companion.state()).avatar.length)).toBeGreaterThan(100);
  await application.evaluate(({BrowserWindow})=>{globalThis.__companionTest.conversationClock.lastActivity=Date.now()-12*3600_000;});
  await page.evaluate(()=>window.companion.action('open','chat'));assert.notEqual((await panel.evaluate(()=>window.companion.state())).sessionId,initialSession);
  assert.equal(await panel.evaluate(()=>typeof window.require),'undefined');
  await panel.locator('#messageInput').fill('你好，陪我学习一下');await panel.locator('#send').click();
  await expect.poll(()=>panel.evaluate(async()=>!(await window.companion.state()).busy)).toBe(true);
  await expect.poll(()=>panel.evaluate(async()=>(await window.companion.history()).length)).toBeGreaterThanOrEqual(2);
  await panel.waitForFunction(()=>document.querySelector('#messages')?.textContent?.includes('我在这里陪着你'));
  const history=await panel.evaluate(()=>window.companion.history());
  await panel.evaluate(id=>window.companion.action('forget',id),history[0].id);
  assert.equal((await panel.evaluate(()=>window.companion.history())).some(m=>m.id===history[0].id),false);
  await panel.evaluate(()=>window.companion.action('settings',{allowDrag:true,walking:false}));
  await panel.locator('#hideDesktop').click();await expect(panel.locator('#hideDesktop')).toHaveText('显示桌面伙伴');
  const restore=application.windows().find(p=>p.url().includes('view=restore'));await restore.locator('#restorePet').click();await expect(panel.locator('#hideDesktop')).toHaveText('隐藏桌面伙伴');
  await panel.locator('#dndToggle').click();await expect(panel.locator('#dndToggle')).toHaveText('退出勿扰');await panel.locator('#dndToggle').click();
  assert.equal(await panel.locator('#dndToggle').count(),1);assert.equal(await panel.locator('[data-tab="learning"]').count(),0);
  await panel.locator('#learnStart').click();await panel.locator('#learnQuiet').click();await expect(panel.locator('#learnStart')).toHaveText('安静陪伴 · 已开启');await expect(panel.locator('#learnStop')).toBeVisible();
  await panel.locator('#learnStop').click();await expect(panel.locator('#learnStop')).toBeHidden();assert.equal((await panel.evaluate(()=>window.companion.state())).learning.active,false);
  await panel.evaluate(()=>window.companion.action('chat','[断网]'));
  await expect.poll(()=>panel.evaluate(async()=>!(await window.companion.state()).busy)).toBe(true);
  await panel.evaluate(()=>window.companion.action('chat','停止测试'));
  await expect.poll(()=>panel.evaluate(async()=>(await window.companion.state()).busy)).toBe(true);
  await panel.evaluate(()=>window.companion.action('cancel'));await expect.poll(()=>panel.evaluate(async()=>!(await window.companion.state()).busy)).toBe(true);
  await panel.locator('[data-tab="settings"]').click();await panel.waitForSelector('#editCharacter');
  for(const theme of ['blue','dark','sakura']){await panel.locator(`[data-theme="${theme}"]`).click();await expect.poll(()=>panel.evaluate(()=>document.documentElement.dataset.theme)).toBe(theme);}
  await panel.locator('#bubbleFontSize').fill('20');await panel.locator('#bubbleFontSize').dispatchEvent('change');await expect.poll(()=>panel.evaluate(async()=>(await window.companion.state()).settings.bubbleFontSize)).toBe(20);
  await panel.locator('#editProactive').click();for(const [mode,hour,interval] of [['quiet','1','45'],['normal','2','20'],['active','12','5'],['reply','0','0']]){await panel.locator('#mode').selectOption(mode);await expect(panel.locator('#proactiveHourlyLimit')).toHaveValue(hour);await expect(panel.locator('#proactiveInterval')).toHaveValue(interval);await expect(panel.locator('#proactiveHourlyLimit')).toBeDisabled();}await panel.locator('#mode').selectOption('custom');await expect(panel.locator('#proactiveHourlyLimit')).toBeEnabled();await panel.locator('#proactiveHourlyLimit').fill('4');await panel.locator('#proactiveInterval').fill('35');await panel.locator('#editorSave').click();await expect(panel.locator('.modalOverlay')).toHaveCount(0);assert.equal((await panel.evaluate(()=>window.companion.state())).settings.proactiveInterval,35);
  await mkdir('test-results',{recursive:true});if(!process.env.COMPANION_EXECUTABLE)await panel.screenshot({path:'test-results/settings.png'});
  await panel.locator('[data-tab="model"]').click();await panel.waitForSelector('#saveModel');await expect(panel.locator('#usageRecords')).toBeHidden();await panel.locator('#usageToggle').click();await expect(panel.locator('#usageRecords')).toBeVisible();assert(await panel.locator('#usageRecords tbody tr').count()<=10);
  await panel.locator('#saveModel').click();await expect(panel.locator('#apiKey')).toHaveValue('');await panel.locator('#editorCancel').click();
  await panel.locator('[data-tab="memory"]').click();await panel.waitForSelector('#clearCurrent');await panel.locator('.danger .helpMark').hover();await expect(panel.locator('.danger .tooltip')).toBeVisible();await panel.locator('#pageTitle').hover();await expect(panel.locator('.danger .tooltip')).toBeHidden();
  await panel.locator('#manageMemory').click();await panel.locator('#memoryText').fill('喜欢安静\n\n希望每天读书');await panel.locator('#editorSave').click();await expect(panel.locator('.modalOverlay')).toHaveCount(0);assert.equal((await panel.evaluate(()=>window.companion.memory())).facts.length,2);
  await panel.locator('#updateMemory').click();await expect.poll(()=>panel.evaluate(async()=>!(await window.companion.state()).busy)).toBe(true);await expect(panel.locator('#updateMemory')).toBeEnabled();assert((await panel.evaluate(()=>window.companion.memory())).summaries.length>0);
  await panel.locator('#clearCurrent').click();await expect(panel.locator('[role="dialog"]')).toBeVisible();await panel.locator('#confirmCancel').click();await expect(panel.locator('.modalOverlay')).toHaveCount(0);
  await panel.locator('[data-tab="chat"]').click();if(!process.env.COMPANION_EXECUTABLE)await panel.screenshot({path:'test-results/chat.png'});
  const oldSession=(await panel.evaluate(()=>window.companion.state())).sessionId;await panel.locator('#newChat').click();await expect.poll(()=>panel.evaluate(async()=>(await window.companion.state()).sessionId)).not.toBe(oldSession);await expect(panel.locator('#messages .message')).toHaveCount(0);
  await panel.locator('#chatHistory').click();await expect(panel.locator('.historyRow')).not.toHaveCount(0);await panel.locator('#modalClose').click();
  const menu=await application.evaluate(({Menu})=>Menu.getApplicationMenu());assert.equal(menu,null);
  const pet=application.windows().find(p=>p.url().includes('view=pet'));await panel.locator('[data-tab="model"]').click();await panel.waitForSelector('#saveModel');
  await application.evaluate(({BrowserWindow})=>{for(const w of BrowserWindow.getAllWindows())w.webContents.send('companion:bubble',{text:'这是一个用于验证气泡截断而不滚动的长句子。'.repeat(8)});});await expect(speech.locator('#bubble')).toHaveClass(/visible/);
  assert.equal(await speech.locator('#bubble').evaluate(el=>getComputedStyle(el).overflowY),'hidden');await speech.locator('#bubble').hover();await pet.mouse.wheel(0,250);assert.equal(await speech.locator('#bubble').evaluate(el=>el.scrollTop),0);
  await speech.locator('#bubble').click();await expect(panel.locator('#pageTitle')).toHaveText('聊一聊');
  await application.evaluate(({BrowserWindow})=>{for(const w of BrowserWindow.getAllWindows())w.webContents.send('companion:bubble',{text:'气泡消失测试'});});await expect(speech.locator('#bubble')).toHaveClass(/visible/);await expect(speech.locator('#bubble')).not.toHaveClass(/visible/,{timeout:10000});
  assert.deepEqual(errors,[]);
  const prefs=await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({pet:w.webContents.getURL().includes('view=pet'),background:w.getBackgroundColor(),focusable:w.isFocusable(),prefs:w.webContents.getLastWebPreferences()})));
  assert(prefs.some(w=>w.pet&&!w.focusable));assert(prefs.every(w=>w.prefs.contextIsolation&&w.prefs.sandbox&&!w.prefs.nodeIntegration));
  console.log('PASS: Windows Electron mock chat/cancel/error, floating restore, study start/end, themes/font, custom frequency modal, tooltip dismissal, styled confirmation, history/new session, collapsed paginated costs, fading bubble, no native menu, renderer isolation.');
}finally{await application.close();}
