import {marked} from 'marked';
import DOMPurify from 'dompurify';
import renderMathInElement from 'katex/contrib/auto-render';
import type {State,Action,ChatMessage} from '../shared/types';
import {presets} from '../providers/stream';
import {localDay} from '../costs/budget';
const api=window.companion,app=document.querySelector<HTMLDivElement>('#app')!;
const view=new URLSearchParams(location.search).get('view')??'panel';
document.body.className=view==='bubble'?'speech':view;const isSpeech=view==='bubble';
let state:State,tab='chat',live='',pending=false,privateRequest=false,activeRequest='',privateMessages:{role:string;content:string}[]=[],lastUser='',history:ChatMessage[]=[],selectedSession='',reviewQuestion='',usagePage=0,usageExpanded=false,renderRevision=0;
let bubbleQueue:string[]=[],fragment='',bubbleTimer:ReturnType<typeof setTimeout>|undefined,toastTimer:ReturnType<typeof setTimeout>|undefined;
const esc=(t:any)=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const help=(text:string)=>`<span class="help"><button type="button" class="helpMark" aria-label="帮助">?</button><span class="tooltip" role="tooltip">${esc(text)}</span></span>`;
const field=(id:string,label:string,value:any,type='text',tip='')=>`<label class="field"><span>${label}${tip?help(tip):''}</span><input id="${id}" type="${type}" value="${esc(value??'')}" ${type==='password'?'autocomplete="new-password"':''}></label>`;
const check=(id:string,label:string,value:boolean,tip='')=>`<label class="check"><input id="${id}" type="checkbox" ${value?'checked':''}>${label}${tip?help(tip):''}</label>`;
async function act(action:Action,payload?:any){try{const result=await api.action(action,payload);if(result?.error){toast(result.error);return null;}return result;}catch{toast('操作失败，请重试。');return null;}}
function toast(message:string){if(isSpeech){showBubble(message);return;}let el=$('toast');if(!el){el=document.createElement('div');el.id='toast';document.body.append(el);}clearTimeout(toastTimer);el.textContent=message;el.className='visible';toastTimer=setTimeout(()=>el.className='',4000);}
function markdown(el:HTMLElement,text:string){el.innerHTML=DOMPurify.sanitize(marked.parse(text,{async:false}) as string,{FORBID_TAGS:['img','iframe','style','script','form','input','button'],FORBID_ATTR:['style']});try{renderMathInElement(el,{delimiters:[{left:'$$',right:'$$',display:true},{left:'\\[',right:'\\]',display:true},{left:'$',right:'$',display:false},{left:'\\(',right:'\\)',display:false}],throwOnError:false,trust:false,strict:'ignore'});}catch{}}
let refreshPetFrame:(()=>void)|undefined;
function syncCompanionStatus(){document.body.classList.toggle('isQuiet',state.settings.dnd);const quiet=$<HTMLButtonElement>('petQuiet');if(quiet){quiet.textContent=state.settings.dnd?'醒':'静';quiet.title=state.settings.dnd?'退出勿扰':'开启勿扰';quiet.setAttribute('aria-label',quiet.title);quiet.setAttribute('aria-pressed',String(state.settings.dnd));}$('petStatus')?.setAttribute('aria-label',state.settings.dnd?'勿扰中':'正常陪伴');const avatar=$<HTMLImageElement>('restoreAvatar');if(avatar)avatar.src=state.avatar;refreshPetFrame?.();}
function applyTheme(){syncCompanionStatus();document.documentElement.dataset.theme=state.settings.theme;document.documentElement.style.setProperty('--bubble-font',state.settings.bubbleFontSize+'px');}

let modalCleanup:(()=>void)|undefined;
function closeModal(){modalCleanup?.();modalCleanup=undefined;}
function modal(title:string,body:string,buttons:string,onCancel?:()=>void){
  closeModal();const previousFocus=document.activeElement as HTMLElement|null;
  const overlay=document.createElement('div');overlay.className='modalOverlay';overlay.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialogTitle"><div class="modalHeader"><h2 id="dialogTitle">${esc(title)}</h2><button id="modalClose" aria-label="关闭">×</button></div><div class="modalBody">${body}</div>${buttons?`<div class="modalFooter">${buttons}</div>`:''}</section>`;
  document.body.append(overlay);
  const dismiss=()=>{closeModal();onCancel?.();};
  const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();dismiss();}if(e.key==='Tab'){const items=[...overlay.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea,select,[tabindex="0"]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  document.addEventListener('keydown',keydown);$('modalClose').onclick=dismiss;overlay.onmousedown=e=>{if(e.target===overlay)dismiss();};
  modalCleanup=()=>{document.removeEventListener('keydown',keydown);overlay.remove();previousFocus?.focus();};
  setTimeout(()=>overlay.querySelector<HTMLElement>('input,textarea,select,button')?.focus(),0);
}
function editor(title:string,body:string,save:()=>Promise<boolean|void>){modal(title,body,'<button id="editorCancel">取消</button><button id="editorSave" class="primary">保存</button>');$('editorCancel').onclick=closeModal;$('editorSave').onclick=async()=>{const button=$<HTMLButtonElement>('editorSave');button.disabled=true;try{if(await save()!==false){closeModal();await renderTab();toast('已保存');}}finally{if(button.isConnected)button.disabled=false;}};}
api.on('dialog',event=>{if(view!=='panel')return;if(event.dismiss){closeModal();return;}const reply=(answer:boolean)=>void act('confirm',{id:event.id,answer});modal(event.title,`<p class="dialogDetail">${esc(event.detail)}</p>`,'<button id="confirmCancel">取消</button><button id="confirmAccept" class="'+(event.danger?'destructive':'primary')+'">'+esc(event.accept)+'</button>',()=>reply(false));$('confirmCancel').onclick=()=>{closeModal();reply(false);};$('confirmAccept').onclick=()=>{closeModal();reply(true);};});

function fitBubble(text:string){const el=$('bubble'),style=getComputedStyle(el),measure=el.cloneNode(false) as HTMLElement;measure.removeAttribute('id');Object.assign(measure.style,{position:'fixed',left:'-10000px',bottom:'auto',width:el.getBoundingClientRect().width+'px',height:'auto',maxHeight:'none',visibility:'hidden',display:'block',overflow:'visible',transition:'none'});document.body.append(measure);const capacity=Math.min(isSpeech?110:innerHeight*.36,parseFloat(style.lineHeight)*(!isSpeech&&innerHeight<=200?1:2)+parseFloat(style.paddingTop)+parseFloat(style.paddingBottom)+2),chars=Array.from(text);let lo=1,hi=chars.length;while(lo<hi){const mid=Math.ceil((lo+hi)/2);measure.textContent=chars.slice(0,mid).join('');if(measure.getBoundingClientRect().height<=capacity+.5&&measure.scrollWidth<=measure.clientWidth)lo=mid;else hi=mid-1;}measure.remove();return [chars.slice(0,lo).join(''),chars.slice(lo).join('')];}
function showBubble(text:string){const el=$('bubble');if(!el||!text)return;clearTimeout(bubbleTimer);const [page,remaining]=fitBubble(text);if(remaining)bubbleQueue.unshift(remaining);el.textContent=page;el.classList.add('visible');if(isSpeech)void act('bubble-visibility',{visible:true});const hold=bubbleQueue.length?Math.max(1000,Math.min(2800,Array.from(page).length*90)):Math.max(2800,Math.min(4000,page.length*100));bubbleTimer=setTimeout(()=>{el.classList.remove('visible');bubbleTimer=setTimeout(()=>{el.textContent='';if(!bubbleQueue.length&&isSpeech)void act('bubble-visibility',{visible:false});if(bubbleQueue.length)showBubble(bubbleQueue.shift()!);},180);},hold);}
function queueSentences(text:string,final=false){if(!state.settings.bubbleRotation){if(final){fragment='';bubbleQueue=[];showBubble('回复已放在聊天中。');}return;}fragment+=text;let match:RegExpExecArray|null;while((match=/^[\s\S]*?[。！？!?\n]+/.exec(fragment))){bubbleQueue.push(match[0]);fragment=fragment.slice(match[0].length);}if(final||fragment.length>=80){if(fragment)bubbleQueue.push(fragment);fragment='';}if(bubbleQueue.length&&!$('bubble')?.classList.contains('visible'))showBubble(bubbleQueue.shift()!);}
function reflowBubble(){const el=$('bubble');if(el?.classList.contains('visible')&&el.textContent)showBubble(el.textContent);}
window.addEventListener('resize',reflowBubble);
function createPet(){
  app.innerHTML='<div id="petWrap"><img id="petImage" draggable="false" alt="桌面伙伴"><span id="petStatus" class="petStatus" aria-label="正常陪伴">☾ 勿扰中</span><canvas id="hitCanvas" width="256" height="256" hidden></canvas><div id="petControls" data-hit><button id="chatOpen" aria-label="打开聊天">聊</button><button id="petQuiet" aria-label="切换勿扰">静</button><button id="petHide" aria-label="隐藏伙伴">−</button></div></div>';
  const img=$<HTMLImageElement>('petImage'),canvas=$<HTMLCanvasElement>('hitCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true})!;let pixels:Uint8ClampedArray|null=null,dragging=false,moved=false,pressedOnPet=false,start={x:0,y:0},frame=0,action='idle',actionUntil=0,previewUntil=0,lastFrameAt=0,lastSrc='';
  img.onload=()=>{ctx.clearRect(0,0,256,256);ctx.drawImage(img,0,0,256,256);pixels=ctx.getImageData(0,0,256,256).data;};const update=()=>{const selected=Date.now()<previewUntil?action:state.settings.dnd?'sleep':action,frames=state.character.frames[selected]??state.character.frames.idle;if(Date.now()-lastFrameAt>=(state.character.frameMs?.[selected]??850)){frame++;lastFrameAt=Date.now();}const next=frames[frame%frames.length];if(next!==lastSrc){lastSrc=next;img.src=next;}img.dataset.action=selected;};refreshPetFrame=update;syncCompanionStatus();update();setInterval(()=>{if(Date.now()>actionUntil)action='idle';update();},50);
  let lastHit=false;api.on('pointer',point=>{const e={clientX:point.x,clientY:point.y};const target=document.elementFromPoint(point.x,point.y);const interactive=dragging||!!target?.closest('[data-hit]')||hit(e);if(interactive!==lastHit){lastHit=interactive;api.hit(interactive);}});function hit(e:{clientX:number;clientY:number}){if(!img.complete||!img.naturalWidth)return false;const r=img.getBoundingClientRect(),scale=Math.min(r.width/img.naturalWidth,r.height/img.naturalHeight),width=img.naturalWidth*scale,height=img.naturalHeight*scale,x=Math.floor((e.clientX-r.left-(r.width-width)/2)/width*256),y=Math.floor((e.clientY-r.top-(r.height-height)/2)/height*256);if(x<0||y<0||x>=256||y>=256)return false;ctx.clearRect(0,0,256,256);ctx.drawImage(img,0,0,256,256);return ctx.getImageData(x,y,1,1).data[3]>30;}

  document.addEventListener('mousemove',e=>{const interactive=dragging||!!(e.target as HTMLElement).closest('[data-hit]')||hit(e);if(interactive!==lastHit){lastHit=interactive;api.hit(interactive);}if(dragging){if(Math.abs(e.screenX-start.x)+Math.abs(e.screenY-start.y)>5)moved=true;api.drag('move');}});document.addEventListener('mouseleave',()=>{if(!dragging){lastHit=false;api.hit(false);}});
  $('petWrap').addEventListener('mousedown',e=>{if(e.button!==0||!hit(e))return;pressedOnPet=true;start={x:e.screenX,y:e.screenY};moved=false;if(state.settings.allowDrag){dragging=true;api.drag('start');}});$('petWrap').addEventListener('pointerdown',e=>{if(state.settings.allowDrag&&hit(e))$('petWrap').setPointerCapture(e.pointerId);});document.addEventListener('mouseup',e=>{if(dragging){dragging=false;api.drag('end');}if(pressedOnPet&&!moved&&hit(e)){action='click';actionUntil=Date.now()+1800;void act('open','quick');}pressedOnPet=false;});
  $('chatOpen').onclick=()=>void act('open','chat');$('petQuiet').onclick=()=>void act('settings',{dnd:!state.settings.dnd});$('petHide').onclick=()=>void act('hide');api.on('bubble',event=>{if(event.action){action=event.action;actionUntil=Date.now()+(event.preview?6000:1200);if(event.preview)previewUntil=actionUntil;update();}});
}
async function renderChat(revision=renderRevision){history=await api.history(selectedSession||state.sessionId);if(revision!==renderRevision||tab!=='chat')return;const archived=!!selectedSession&&selectedSession!==state.sessionId;
  $('content').innerHTML=`<section class="chatCard"><div class="chatTop"><b id="chatBuddyName">${esc(state.settings.name)}</b>${archived?'<span class="pill">历史对话</span><button id="backCurrent">回到当前对话</button>':'<span id="studyStatus"></span><button id="learnStart">学习陪伴</button><button id="learnStop" hidden>结束学习</button><button id="retry" class="textButton">重试上一条</button>'}</div><div id="messages" class="messages"></div>${archived?'':`<div class="compose"><div id="attachments"></div><div id="reviewArea"></div><textarea id="messageInput" rows="2" placeholder="想聊些什么？" maxlength="12000"></textarea><div class="composeBottom"><div class="composeTools"><button id="uploadSource">＋ 资料</button><label class="privateLabel"><input id="private" type="checkbox" ${!state.settings.saveHistory?'checked':''}>不保存</label>${help('消息最多12000字符；资料全文最多160000字符。PDF最多20 MB、2000页，文本最多1 MB。回车发送，换挡键加回车换行。')}</div><button id="send" class="primary">${pending?'停止生成':'发送'}</button></div></div>`}</section>`;
  await drawMessages();if(archived){$('backCurrent').onclick=()=>{selectedSession='';void renderTab();};return;}$('send').onclick=()=>void send();$('retry').onclick=()=>{if(lastUser){$<HTMLTextAreaElement>('messageInput').value=lastUser;void send();}};$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}};$('private').onchange=()=>void act('settings',{saveHistory:!$<HTMLInputElement>('private').checked});$('uploadSource').onclick=async()=>{if(await act('document-import')){syncChatTools();toast('已附上完整资料');}};$('learnStart').onclick=showLearning;$('learnStop').onclick=async()=>{if(await act('learning',{active:false,review:false})){reviewQuestion='';syncChatTools();toast('学习已结束');}};syncChatTools();
}
function syncChatTools(){if(view!=='panel'||tab!=='chat'||!$('learnStart'))return;const active=state.learning.active;$('learnStart').textContent=active?(state.learning.review?'偶尔问我 · 已开启':'安静陪伴 · 已开启'):'学习陪伴';$('learnStart').classList.toggle('selected',active);$('learnStop').hidden=!active;$('studyStatus').textContent=active?(state.learning.review?'学习中 · 偶尔问我':'学习中 · 安静陪伴'):'';
  const c=state.context;$('attachments').innerHTML=c?`<button id="sourcePreview" class="attachment">▤ ${esc(c.title)}${c.full_document?' · 全文':c.source_type==='pdf'?' · 第'+c.position+'页':''}<span>${state.settings.contextSend?'已附上':'待授权'}</span></button><button id="sourceRemove" class="textButton" aria-label="移除资料">×</button>`:'';if(c){$('sourcePreview').onclick=showSource;$('sourceRemove').onclick=()=>void act('context-revoke');}
  $('reviewArea').innerHTML=reviewQuestion?`<div class="review"><div id="reviewText"></div><div class="buttonRow"><button data-review="self">已在心里复习</button><button data-review="answer">看答案</button><button data-review="today">今天不抽问</button></div></div>`:'';if(reviewQuestion){$('reviewText').textContent=reviewQuestion;document.querySelectorAll<HTMLButtonElement>('[data-review]').forEach(b=>b.onclick=async()=>{if(await act('review-response',b.dataset.review)){reviewQuestion='';syncChatTools();}});}
}
async function drawMessages(){if(tab!=='chat'||view!=='panel')return;const el=$('messages');if(!el)return;el.innerHTML='';const archived=!!selectedSession&&selectedSession!==state.sessionId;const all=[...history,...(archived?[]:privateMessages)];if(!all.length&&!live)el.innerHTML=`<div class="welcome"><img src="${state.character.frames.idle[0]}" alt="${esc(state.settings.name)}"><h2>今天想聊些什么？</h2><div class="suggestions"><button data-suggestion="我有点累，想聊一会儿。">聊聊今天</button><button id="welcomeStudy">陪我学习</button></div></div>`;
  for(const m of all){const row=document.createElement('article');row.className='message '+m.role;const status='status' in m?({cancelled:'已停止',error:'未完成',excluded:'不用于记忆'} as any)[String(m.status)]??'':'';row.innerHTML=`<div class="messageLabel">${m.role==='user'?'你':esc(state.settings.name)}${status?' · '+status:''}</div><div class="prose"></div>`;markdown(row.querySelector('.prose')!,m.content);if('id' in m){const button=document.createElement('button');button.className='forget textButton';button.textContent='不要记这条';button.onclick=async()=>{if(await act('forget',m.id)){history=await api.history(selectedSession||state.sessionId);await drawMessages();}};row.append(button);}el.append(row);}
  if(live&&!archived){const row=document.createElement('article');row.className='message assistant';row.innerHTML=`<div class="messageLabel">${esc(state.settings.name)}${pending?' · 正在回应':''}</div><div class="prose"></div>`;markdown(row.querySelector('.prose')!,live);el.append(row);}el.querySelectorAll<HTMLButtonElement>('[data-suggestion]').forEach(b=>b.onclick=()=>{$<HTMLTextAreaElement>('messageInput').value=b.dataset.suggestion!;void send();});if($('welcomeStudy'))$('welcomeStudy').onclick=showLearning;el.scrollTop=el.scrollHeight;
}
async function send(){if(pending){await act('cancel');return;}const input=$<HTMLTextAreaElement>('messageInput'),text=input.value.trim();if(!text)return;lastUser=text;input.value='';await act('chat',text);}
async function showHistory(){const mem=await api.memory();modal('聊天历史',`<div class="historyList">${mem.sessions.length?mem.sessions.map((s:any)=>`<div class="historyRow"><button data-session="${esc(s.session_id)}"><b>${esc(s.title)}</b><span>${new Date(s.updated_at).toLocaleString('zh-CN')} · ${s.count}条</span></button><button class="textButton" data-forget-session="${esc(s.session_id)}">删除</button></div>`).join(''):'<div class="empty">还没有历史对话</div>'}</div>`,'');document.querySelectorAll<HTMLButtonElement>('[data-session]').forEach(b=>b.onclick=()=>{selectedSession=b.dataset.session!;closeModal();void renderTab();});document.querySelectorAll<HTMLButtonElement>('[data-forget-session]').forEach(b=>b.onclick=async()=>{const id=b.dataset.forgetSession!;if(await act('summary-delete',id)){if(selectedSession===id)selectedSession='';await showHistory();await renderTab();}});}
function showLearning(){modal('学习陪伴',`<div class="choiceCards"><button id="learnQuiet" class="choice ${state.learning.active&&!state.learning.review?'selected':''}"><strong>安静陪伴</strong><span>在身边，不抽问</span></button><button id="learnReview" class="choice ${state.learning.active&&state.learning.review?'selected':''}"><strong>偶尔问我</strong><span>分享资料后，偶尔回顾</span></button></div>`,'');for(const [id,review] of [['learnQuiet',false],['learnReview',true]] as const)$(id).onclick=async()=>{closeModal();if(await act('learning',{active:true,review})){syncChatTools();toast(review?'已开启偶尔问我':'已开启安静陪伴');}};}
function showSource(){const c=state.context;if(!c)return;if(c.full_document){modal('聊天资料',`<h3>${esc(c.title)}</h3><div class="excerpt">${esc(c.content_excerpt)}</div>`,'<button id="sourceDone" class="primary">完成</button>');$('sourceDone').onclick=closeModal;return;}modal('聊天资料',`<h3>${esc(c.title)}</h3>${c.source_type==='pdf'?`<div class="pageControl">${field('pdfPage','页码',c.position,'number')}<button id="pageGo">切换页</button></div>`:''}<div class="excerpt">${esc(c.content_excerpt??'没有提取到文字，请使用文本资料。')}</div>${check('contextSend','附上此片段',state.settings.contextSend,'选定片段将随聊天发送给当前模型，可随时移除。')}`,'<button id="sourceDone" class="primary">完成</button>');$('sourceDone').onclick=closeModal;$('contextSend').onchange=async()=>{const selected=$<HTMLInputElement>('contextSend').checked;closeModal();await act('settings',{contextSend:selected});syncChatTools();};if($('pageGo'))$('pageGo').onclick=async()=>{if(await act('pdf-page',Number($<HTMLInputElement>('pdfPage').value)))showSource();};}
function renderMemory(mem:any){$('content').innerHTML=`<section class="card"><div class="cardHeading"><h2>记忆管理</h2>${help('按完整会话整理，自动更新最多每天一次。可手动更新，也可修改、删除记忆。')}</div><div id="facts"></div></section><section class="card"><div class="settingRow"><div><b>自动整理记忆</b></div>${check('memoryEnabled','开启',state.settings.memoryEnabled)}</div><div class="buttonRow"><button id="exportData">导出备份</button><button id="importData">导入备份</button></div></section><section class="card danger"><div class="cardHeading"><h2>清空记忆</h2>${help('同时删除聊天、摘要和关联记忆。清空后无法恢复，建议先导出备份。')}</div><div class="buttonRow"><button id="clearCurrent" class="destructive">清空当前伙伴</button><button id="clearAll" class="destructive outline">清空全部伙伴</button></div></section>`;
  $('facts').innerHTML=`<div class="settingRow"><span>${mem.facts.length}条记忆</span><button id="manageMemory">记忆管理</button></div><div class="buttonRow"><button id="updateMemory">更新记忆</button>${help('自动更新最多每天一次，合并最多4个完整会话，每批最多160000字符。手动更新可包含当前对话，会产生模型费用。')}</div>`;
  $('manageMemory').onclick=()=>{editor('记忆管理',`<label class="field full"><span>记忆内容${help('最多6000字符。空行分隔记忆，可直接修改或删除。')}</span><textarea id="memoryText" rows="12" maxlength="6000">${esc(mem.facts.map((f:any)=>f.content).join('\n\n'))}</textarea></label><span id="memoryCapacity" class="muted"></span>`,async()=>!!await act('memory-save',$<HTMLTextAreaElement>('memoryText').value));const count=()=>{$('memoryCapacity').textContent=$<HTMLTextAreaElement>('memoryText').value.length+' / 6000';};$('memoryText').oninput=count;count();};
  $('updateMemory').onclick=async()=>{const button=$<HTMLButtonElement>('updateMemory');button.disabled=true;button.textContent='正在更新…';const result=await act('memory-update');await renderTab();if(result)toast(result.updated?'记忆已更新':'没有待整理的聊天');};
  $('memoryEnabled').onchange=()=>void act('settings',{memoryEnabled:$<HTMLInputElement>('memoryEnabled').checked});$('exportData').onclick=async()=>{if(await act('export'))toast('备份已导出');};$('importData').onclick=async()=>{if(await act('import'))await renderTab();};$('clearCurrent').onclick=async()=>{if(await act('clear','current'))await renderTab();};$('clearAll').onclick=async()=>{if(await act('clear','all'))await renderTab();};
}
const money=(value:number)=>'¥'+value.toFixed(value<0.01?5:2);
function renderModel(mem:any){const s=state.settings,records=mem.usage.filter((r:any)=>r.provider!=='mock'),today=records.filter((r:any)=>localDay(r.created_at)===localDay()),month=records.filter((r:any)=>localDay(r.created_at).slice(0,7)===localDay().slice(0,7));const total=(rows:any[])=>money(rows.reduce((a:number,r:any)=>a+(r.cost??0),0));const unknown=today.filter((r:any)=>r.cost===null).length;
  $('content').innerHTML=`<section class="card"><div class="settingRow"><div><h2>${esc(s.provider==='mock'?'离线演示':presets[s.provider]?.label??s.provider)}</h2><span class="muted">${esc(s.model||'尚未选择模型')}</span></div><div class="buttonRow settingButtons"><button id="manageKeys">密钥管理</button><button id="saveModel">配置模型</button></div></div><div class="buttonRow"><button id="deepseekHelp" class="textButton">DeepSeek API 官网 ↗</button></div></section><div class="grid2"><section class="card"><div class="cardHeading"><span>今日估算</span>${help('根据供应商返回的用量和价目估算，并非账户实际扣费。官方价目使用高峰价格，空闲时段实际费用可能更低。')}</div><div class="costNumber">${today.length&&unknown===today.length?'待计算':total(today)}</div>${unknown?'<span class="muted">另有'+unknown+'次费用未知</span>':''}</section><section class="card"><span>本月估算</span><div class="costNumber">${total(month)}</div>${month.some((r:any)=>r.cost===null)?'<span class="muted">部分调用费用未知</span>':''}</section></div><section class="card"><div class="settingRow"><div><b>费用与预算</b><div class="settingValue">${s.inputPrice===null?'尚无价目':`输入 ${s.inputPrice} / 输出 ${s.outputPrice} 元每百万令牌`}</div></div><button id="editBudget">设置</button></div><div class="buttonRow"><button id="refreshPrices">更新官方价目</button>${s.priceCheckedAt?'<span class="muted">更新于 '+new Date(s.priceCheckedAt).toLocaleDateString('zh-CN')+'</span>':''}</div></section><section class="card"><button id="usageToggle" class="disclosure" aria-expanded="${usageExpanded}">${usageExpanded?'收起':'查看'}调用记录 <span>${mem.usage.length}次</span></button><div id="usageRecords" ${usageExpanded?'':'hidden'}></div></section>`;
  $('manageKeys').onclick=()=>{modal('密钥管理',`<div class="importChoices">${state.keyProviders.length?state.keyProviders.map(id=>`<div class="settingRow"><b>${esc(presets[id as keyof typeof presets]?.label??'离线演示')}</b><button class="destructive" data-delete-key="${id}">删除</button></div>`).join(''):'<p>尚未保存密钥</p>'}</div>`,'<button id="replaceKey" class="primary">添加或替换</button>');$('replaceKey').onclick=showModelEditor;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-delete-key]'))b.onclick=async()=>{const id=b.dataset.deleteKey;closeModal();if(await act('key-delete',id)){await renderTab();toast('密钥已删除');}};};$('saveModel').onclick=showModelEditor;$('deepseekHelp').onclick=()=>void act('external-link','https://platform.deepseek.com/api_keys');$('editBudget').onclick=showBudgetEditor;$('refreshPrices').onclick=async()=>{const b=$<HTMLButtonElement>('refreshPrices');b.disabled=true;b.textContent='正在更新…';if(await act('prices-refresh')){await renderTab();toast('价目已更新');}else{b.disabled=false;b.textContent='更新官方价目';}};$('usageToggle').onclick=()=>{usageExpanded=!usageExpanded;renderModel(mem);};if(usageExpanded)drawUsage(mem.usage);
}
function drawUsage(records:any[]){const pages=Math.max(1,Math.ceil(records.length/10));usagePage=Math.min(usagePage,pages-1);const rows=records.slice(usagePage*10,usagePage*10+10);$('usageRecords').innerHTML=`<div class="tableWrap"><table><thead><tr><th>时间</th><th>用途</th><th>输入 / 输出</th><th>估算费用</th><th>状态</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('zh-CN')}</td><td>${esc(({chat:'聊天',summary:'记忆整理',proactive:'主动陪伴'} as any)[r.kind]??'其他')}<small>${esc(r.model)}</small></td><td>${r.input??'未知'} / ${r.output??'未知'}</td><td>${r.provider==='mock'?'离线演示':r.cost===null?'未知':money(r.cost)}</td><td>${esc(({done:'完成',pending:'进行中',cancelled:'已停止',error:'失败'} as any)[r.status]??'未知')}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><button id="usagePrev" ${usagePage===0?'disabled':''}>上一页</button><span>${usagePage+1} / ${pages}</span><button id="usageNext" ${usagePage+1>=pages?'disabled':''}>下一页</button></div>`;$('usagePrev').onclick=()=>{usagePage--;drawUsage(records);};$('usageNext').onclick=()=>{usagePage++;drawUsage(records);};}
function showModelEditor(){const s=state.settings;editor('连接模型',`<div class="formGrid"><label class="field">模型服务<select id="provider">${Object.entries(presets).map(([id,p])=>`<option value="${id}" ${s.provider===id?'selected':''}>${esc(p.label)}</option>`).join('')}<option value="mock" ${s.provider==='mock'?'selected':''}>离线演示</option></select></label>${field('model','模型名称',s.model)}${field('apiKey','填写或替换密钥','','password')}<div class="field"><span>${state.credentialConfigured?'密钥已保存':'尚未保存密钥'}</span><button id="deleteKey" class="destructive" ${state.credentialConfigured?'':'disabled'}>删除密钥</button></div>${field('baseUrl','服务地址',s.baseUrl)}</div>`,async()=>{const input=$<HTMLInputElement>('apiKey'),apiKey=input.value;input.value='';return !!await act('settings',{provider:$<HTMLSelectElement>('provider').value,model:$<HTMLInputElement>('model').value.trim(),baseUrl:$<HTMLInputElement>('baseUrl').value.trim(),apiKey});});$('deleteKey').onclick=async()=>{closeModal();if(await act('key-delete')){await renderTab();toast('密钥已删除');}};$('provider').onchange=()=>{const p=presets[$<HTMLSelectElement>('provider').value as keyof typeof presets];if(p){$<HTMLInputElement>('baseUrl').value=p.url;$<HTMLInputElement>('model').value='';}$<HTMLInputElement>('apiKey').value='';};}
function showBudgetEditor(){const s=state.settings;editor('费用与预算',`<div class="formGrid">${field('dailyBudget','每日预算（元）',s.dailyBudget,'number','留空不设金额上限。存在未知费用时，金额预算会暂停后续调用。')}${field('maxOutputTokens','单次回复上限',s.maxOutputTokens,'number','范围64–4096令牌，影响回复长度和费用。')}${field('backgroundDailyLimit','每日后台调用上限',s.backgroundDailyLimit,'number','范围0–2000次。')}${check('autoPricing','使用官方价目',s.priceSource!=='manual','DeepSeek 官方服务可读取价目，其余服务请填写单价。')}<div class="full grid2">${field('inputPrice','输入单价',s.inputPrice,'number')}${field('outputPrice','输出单价',s.outputPrice,'number')}${field('cachedInputPrice','缓存输入单价',s.cachedInputPrice,'number','单位为元每百万令牌；留空时按普通输入单价估算。')}</div></div>`,async()=>{const raw:any={dailyBudget:numberOrNull('dailyBudget'),maxOutputTokens:Number($<HTMLInputElement>('maxOutputTokens').value),backgroundDailyLimit:Number($<HTMLInputElement>('backgroundDailyLimit').value)};if($<HTMLInputElement>('autoPricing').checked)raw.autoPricing=true;else for(const k of ['inputPrice','outputPrice','cachedInputPrice'])raw[k]=numberOrNull(k);return !!await act('settings',raw);});}
function numberOrNull(id:string){return $<HTMLInputElement>(id).value===''?null:Number($<HTMLInputElement>(id).value);}
function renderSettings(mem:any){const s=state.settings;const proactive=s.mode==='reply'?'仅回答':s.mode==='custom'?`每小时最多${s.proactiveHourlyLimit}次 · 间隔${s.proactiveInterval}分钟`:({quiet:'安静',normal:'适中',active:'活跃'} as any)[s.mode];
  $('content').innerHTML=`<section class="card"><h2>外观</h2><div class="themeChoices">${[['sakura','樱花粉'],['blue','晴空蓝'],['dark','夜色黑']].map(([id,label])=>`<button data-theme="${id}" class="themeChoice ${s.theme===id?'selected':''}" aria-pressed="${s.theme===id}"><span class="swatch ${id}"></span>${label}</button>`).join('')}</div><div class="settingRow"><div><b>气泡字体</b><div class="settingValue">${s.bubbleFontSize} 像素</div></div><input id="bubbleFontSize" type="range" min="12" max="24" value="${s.bubbleFontSize}" aria-label="气泡字体大小"></div></section><section class="card"><div class="settingRow"><div><b>${esc(s.name)}</b><div class="settingValue">${mem.characters.length}个角色</div></div><div class="buttonRow settingButtons"><button id="manageCharacters">角色管理</button><button id="editCharacter">人格设置</button></div></div><div class="settingRow"><div><b>主动陪伴</b><div class="settingValue">${esc(state.proactiveStatus)}</div></div><button id="editProactive">设置</button></div><div class="settingRow"><div><b>桌面表现</b><div class="settingValue">${s.scale}倍大小${s.allowDrag?' · 可拖动':''}</div></div><button id="editDesktop">设置</button></div></section><section class="card"><div class="settingRow"><div><b>隐私与资料权限</b></div><button id="editPermissions">设置</button></div><div class="settingRow"><div><b>浏览器资料</b><div class="settingValue">${s.browserPermission?'允许连接':'未连接'}</div></div><button id="browserSetup">连接设置</button></div></section>`;
  document.querySelectorAll<HTMLButtonElement>('button[data-theme]').forEach(b=>b.onclick=async()=>{if(await act('settings',{theme:b.dataset.theme}))await renderTab();});$('bubbleFontSize').oninput=()=>{const value=Number($<HTMLInputElement>('bubbleFontSize').value);$('bubbleFontSize').previousElementSibling!.querySelector('.settingValue')!.textContent=value+' 像素';};$('bubbleFontSize').onchange=()=>void act('settings',{bubbleFontSize:Number($<HTMLInputElement>('bubbleFontSize').value)});$('manageCharacters').onclick=()=>showCharacterManager(mem);$('editCharacter').onclick=()=>showCharacterEditor(mem);$('editProactive').onclick=showProactiveEditor;$('editDesktop').onclick=showDesktopEditor;$('editPermissions').onclick=showPermissionEditor;$('browserSetup').onclick=showBrowserSetup;
}
async function showCharacterManager(initial?:any){const mem=initial??await api.memory();modal('角色管理',`<div class="characterGrid">${mem.characters.map((p:any)=>`<section class="characterTile ${p.id===state.settings.characterId?'selected':''}"><img src="${p.avatar}" alt="${esc(p.name)}"><b>${esc(p.name)}</b><span class="muted">${p.messages}条聊天 · ${p.memories}条记忆</span><div class="buttonRow"><button data-character="${esc(p.id)}" ${p.id===state.settings.characterId?'disabled':''}>${p.id===state.settings.characterId?'使用中':'切换'}</button><button data-character-edit="${esc(p.id)}">编辑</button><button class="destructive" data-character-delete="${esc(p.id)}" ${mem.characters.length===1?'disabled':''}>删除</button></div></section>`).join('')}</div><div class="buttonRow"><button id="addCharacter" class="primary">＋ 添加角色</button><button id="manageActions">动作管理</button>${help('切换角色保留各自的聊天和记忆。删除角色会一并删除它的记录，至少保留一个角色。')}</div>`,'');
 for(const button of document.querySelectorAll<HTMLButtonElement>('[data-character]'))button.onclick=async()=>{if(await act('character-select',button.dataset.character)){closeModal();await renderTab();toast('已切换到'+state.settings.name);}};
 for(const button of document.querySelectorAll<HTMLButtonElement>('[data-character-edit]'))button.onclick=async()=>{if(await act('character-select',button.dataset.characterEdit)){showCharacterEditor(await api.memory());}};
 for(const button of document.querySelectorAll<HTMLButtonElement>('[data-character-delete]'))button.onclick=async()=>{const result=await act('character-delete',button.dataset.characterDelete);await renderTab();await showCharacterManager();if(result)toast('角色已删除');};
 $('addCharacter').onclick=()=>showCharacterImport();
 $('manageActions').onclick=()=>void showActionManager();
}
function showCharacterImport(){modal('添加角色',`<div class="importChoices"><button id="newImageCharacter"><b>图片或动图</b><span>用一张图片创建新的伙伴</span></button><button id="managerImportPack"><b>完整角色包</b><span>导入包含人格和动作的角色包</span></button></div>`, '');
 const run=async(a:Action,payload?:any)=>{closeModal();if(await act(a,payload)){await renderTab();showCharacterEditor(await api.memory());}};
 $('newImageCharacter').onclick=()=>{editor('用图片添加角色',`${field('newCharacterName','角色名字','新伙伴','text','1–40字符。')}<p>选择图片后创建独立角色。</p>${help('支持PNG、GIF、WebP；最多8 MB，4096×4096像素。')}`,async()=>{const name=$<HTMLInputElement>('newCharacterName').value.trim();closeModal();if(await act('image-import',{newCharacter:true,name})){await renderTab();setTimeout(async()=>showCharacterEditor(await api.memory()),0);return true;}return false;});$('editorSave').textContent='选择图片并创建';};
 $('managerImportPack').onclick=()=>{modal('导入角色包',`<p>选择包含人格和动作的角色包，创建新的伙伴。</p>${help('ZIP最多20 MB；包内总量80 MB，须有角色清单和图片动作。')}`,'<button id="chooseCharacterPack" class="primary">选择角色包</button>');$('chooseCharacterPack').onclick=()=>void run('character-import');};
}
function showActionManager(){const names={idle:'待机',walk:'走动',click:'点击回应',sleep:'安静休息',read:'学习陪伴'} as const;editor('动作管理',`<div class="formGrid"><label class="field full">动作<select id="actionName">${Object.entries(names).map(([id,name])=>`<option value="${id}">${name}${state.character.frames[id]?' · 已设置':''}</option>`).join('')}</select></label>${field('actionFrameMs','每帧间隔（毫秒）',150,'number','范围50–2000毫秒。PNG序列按文件名顺序播放，最多60帧；GIF或WebP自带播放速度。')}</div><div class="actionPreview"><img id="actionPreviewImage" alt="动作预览"></div><div class="buttonRow"><button id="importAction">导入动作</button><button id="previewAction">在桌面预览</button>${help('单选GIF/WebP动图或多选PNG序列。每张最多8 MB、4096×4096，总计最多80 MB。导入只更新当前角色的这个动作，不改人设或记忆。')}</div>`,async()=>true);
 let timer:ReturnType<typeof setInterval>|undefined;const originalCleanup=modalCleanup;modalCleanup=()=>{clearInterval(timer);originalCleanup?.();};const update=()=>{clearInterval(timer);const action=$<HTMLSelectElement>('actionName').value,frames=state.character.frames[action]??state.character.frames.idle;let i=0,last='';const draw=()=>{const source=frames[i++%frames.length];if(last!==source){last=source;$<HTMLImageElement>('actionPreviewImage').src=source;}};draw();$<HTMLInputElement>('actionFrameMs').value=String(state.character.frameMs?.[action]??150);timer=setInterval(draw,state.character.frameMs?.[action]??150);};$('actionName').onchange=update;update();$('importAction').onclick=async()=>{const action=$<HTMLSelectElement>('actionName').value,frameMs=Number($<HTMLInputElement>('actionFrameMs').value);if(await act('action-import',{action,frameMs})){showActionManager();$<HTMLSelectElement>('actionName').value=action;$('actionName').dispatchEvent(new Event('change'));toast('动作已导入');}};$('previewAction').onclick=()=>void act('action-preview',$<HTMLSelectElement>('actionName').value);
}
function showCharacterEditor(mem:any){const s=state.settings;editor('伙伴与人格',`<div class="formGrid">${field('name','伙伴名字',s.name,'text','最多40字符。')}<label class="field full">人格描述${help('最多8000字符。')}<textarea id="persona" rows="4" maxlength="8000">${esc(s.persona)}</textarea></label><label class="field full">点击问候语${help('每行一条，最多20条，每条最多120字符；点击时依次轮换，不调用模型。')}<textarea id="greetings" rows="4" maxlength="2420">${esc(state.character.greetings.join('\n'))}</textarea></label></div><div class="buttonRow"><button id="personaImport">导入人格</button></div>`,async()=>{const payload={name:$<HTMLInputElement>('name').value.trim(),persona:$<HTMLTextAreaElement>('persona').value,greetings:$<HTMLTextAreaElement>('greetings').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)};closeModal();return !!await act('settings',payload);});$('personaImport').onclick=async()=>{closeModal();await act('persona-import');await renderTab();};}
function showProactiveEditor(){const s=state.settings;editor('主动陪伴',`<div class="formGrid">${check('backgroundAI','允许主动陪伴',s.backgroundAI,'开启后偶尔主动聊天、提醒休息或复习；会产生模型费用，受预算限制。')}<label class="field full">陪伴方式<select id="mode">${[['quiet','安静'],['normal','适中'],['active','活跃'],['custom','自定义'],['reply','仅回答']].map(([id,label])=>`<option value="${id}" ${s.mode===id?'selected':''}>${label}</option>`).join('')}</select></label>${field('proactiveHourlyLimit','每小时最多几次',s.proactiveHourlyLimit,'number','范围0–120次，只有自定义模式可修改。')}${field('proactiveInterval','最小间隔（分钟）',s.proactiveInterval,'number','范围0.1–180分钟（0.1分钟为6秒），只有自定义模式可修改。')}</div><div class="buttonRow"><button id="todayQuiet">今天不主动</button><button id="restoreQuiet">恢复默认设置</button><button id="previewProactive">现在主动说一句</button><button id="fastProactive">快速测试</button></div>`,async()=>!!await act('settings',{backgroundAI:$<HTMLInputElement>('backgroundAI').checked,mode:$<HTMLSelectElement>('mode').value,...($<HTMLSelectElement>('mode').value==='custom'?{proactiveHourlyLimit:Number($<HTMLInputElement>('proactiveHourlyLimit').value),proactiveInterval:Number($<HTMLInputElement>('proactiveInterval').value)}:{})}));const sync=()=>{const mode=$<HTMLSelectElement>('mode').value,custom=mode==='custom',limits=({quiet:[1,45],normal:[2,20],active:[12,5],reply:[0,0]} as any)[mode];if(limits){$<HTMLInputElement>('proactiveHourlyLimit').value=String(limits[0]);$<HTMLInputElement>('proactiveInterval').value=String(limits[1]);}for(const id of ['proactiveHourlyLimit','proactiveInterval'])$<HTMLInputElement>(id).disabled=!custom;};$('mode').onchange=sync;sync();$('fastProactive').onclick=()=>{$<HTMLInputElement>('backgroundAI').checked=true;$<HTMLSelectElement>('mode').value='custom';sync();$<HTMLInputElement>('proactiveHourlyLimit').value='120';$<HTMLInputElement>('proactiveInterval').value='0.1';};$('previewProactive').onclick=async()=>{if(!await act('settings',{backgroundAI:$<HTMLInputElement>('backgroundAI').checked,mode:$<HTMLSelectElement>('mode').value,...($<HTMLSelectElement>('mode').value==='custom'?{proactiveHourlyLimit:Number($<HTMLInputElement>('proactiveHourlyLimit').value),proactiveInterval:Number($<HTMLInputElement>('proactiveInterval').value)}:{})}))return;if(await act('proactive-preview'))toast('已主动打招呼');};$('todayQuiet').onclick=async()=>{if(await act('settings',{todayQuiet:localDay()})){closeModal();await renderTab();toast('今天不再主动打扰');}};$('restoreQuiet').onclick=async()=>{if(await act('settings',{mode:'normal',proactiveHourlyLimit:2,proactiveInterval:20,todayQuiet:'',dnd:false,backgroundAI:false})){closeModal();await renderTab();toast('已恢复默认设置');}};}
function showDesktopEditor(){const s=state.settings;editor('桌面表现',`<div class="formGrid"><label class="field full">伙伴大小${help('范围0.5–2倍。')}<input id="scale" type="range" min="0.5" max="2" step="0.1" value="${s.scale}"></label>${check('alwaysOnTop','保持置顶',s.alwaysOnTop)}${check('allowDrag','允许拖动',s.allowDrag)}${check('walking','轻轻走动',s.walking)}${check('bubbleRotation','分句显示回复',s.bubbleRotation)}</div>`,async()=>{const raw:any={scale:Number($<HTMLInputElement>('scale').value)};for(const id of ['alwaysOnTop','allowDrag','walking','bubbleRotation'])raw[id]=$<HTMLInputElement>(id).checked;return !!await act('settings',raw);});}
function showPermissionEditor(){const s=state.settings;editor('隐私与资料权限',`<div class="formGrid">${check('saveHistory','保存聊天历史',s.saveHistory)}${check('memoryEnabled','自动整理记忆',s.memoryEnabled,'结束的已保存会话由模型提取有用记忆，费用计入后台调用。')}${check('foregroundPermission','读取当前应用',s.foregroundPermission,'读取前台应用名称和窗口标题，用于资料状态和自动隐藏规则。')}${check('browserPermission','接收浏览器分享',s.browserPermission)}</div>`,async()=>{const raw:any={};for(const id of ['saveHistory','memoryEnabled','foregroundPermission','browserPermission'])raw[id]=$<HTMLInputElement>(id).checked;return !!await act('settings',raw);});}
function showBrowserSetup(){const p=state.pairing;modal('浏览器连接',p?`<div class="formGrid">${field('pairPort','连接端口',p.port)}${field('pairCode','配对码',p.token)}</div><div class="buttonRow"><button id="pairReset">重新配对</button></div>${help('在浏览器扩展弹窗中填写端口和配对码。配对码仅用于本机资料连接。')}`:'<div class="empty">开启浏览器分享后可进行配对。</div>',p?'':'<button id="enableBrowser" class="primary">开启浏览器分享</button>');if(p){$('pairReset').onclick=async()=>{if(await act('pair-reset'))showBrowserSetup();};}else $('enableBrowser').onclick=async()=>{if(await act('settings',{browserPermission:true}))showBrowserSetup();};}
function createQuick(){app.innerHTML=`<div class="quickCard"><div class="quickTop"><b id="quickName">${esc(state.settings.name)}</b><button id="fullOpen" class="textButton">打开聊天 ↗</button></div><textarea id="quickInput" rows="2" placeholder="想说点什么？" maxlength="12000"></textarea><div class="quickBottom"><span id="quickStatus"></span><button id="quickSend" class="primary">发送</button></div></div>`;const sendQuick=async()=>{if(state.busy){await act('cancel');return;}const input=$<HTMLTextAreaElement>('quickInput');if(input.value.trim()){await act('chat',input.value.trim());input.value='';}};$('quickSend').onclick=()=>void sendQuick();$('quickInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void sendQuick();}};$('fullOpen').onclick=()=>void act('open','chat');}
function showGuide(){const done=()=>void act('settings',{onboardingSeen:true});modal('欢迎，小栖在这里', '<div class="guideSteps"><p>在输入框旁分享完整资料，在聊天上方开启学习陪伴。</p><p>完整会话的记忆最多每天自动更新一次，也可以手动更新，计入模型费用。你随时可以修改、删除或关闭。</p><p>隐藏伙伴后，点击桌面上的头像即可恢复。</p></div>', '<button id="guideDone" class="primary">开始使用</button>',done);$('guideDone').onclick=()=>{closeModal();done();};}
function shell(){
  app.innerHTML=`<aside class="sidebar"><div class="brand"><button id="changeAvatar" class="avatarButton" aria-label="更换头像"><img id="brandAvatar" src="${state.avatar}" alt="伙伴头像"></button>${help('头像最多8 MB、4096×4096，默认居中裁剪。')}<div id="brandName">${esc(state.settings.name)}</div></div><nav>${[['chat','聊一聊'],['memory','记忆管理'],['model','模型与费用'],['settings','伙伴设置']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav><div class="sidebarBottom"><div id="connection"></div><button id="hideDesktop"></button><button id="dndToggle"></button></div></aside><main><header><h1 id="pageTitle"></h1><div class="headerActions" id="headerActions"></div></header><div id="content"></div></main>`;
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(btn=>btn.onclick=()=>{tab=btn.dataset.tab!;void renderTab();});$('hideDesktop').onclick=()=>void act(state.hidden?'show':'hide');$('dndToggle').onclick=()=>void act('settings',{dnd:!state.settings.dnd});$('changeAvatar').onclick=()=>void act('avatar-import');syncHeader();
}
function syncHeader(){if(view!=='panel'||!$('hideDesktop'))return;$('brandName').textContent=state.settings.name;$<HTMLImageElement>('brandAvatar').src=state.avatar;if($('chatBuddyName'))$('chatBuddyName').textContent=state.settings.name;$('connection').innerHTML=`<span class="dot ${state.keyConfigured?'online':''}"></span>${state.settings.provider==='mock'?'离线演示':state.keyConfigured?'模型已配置':'未连接模型'}`;$('hideDesktop').textContent=state.hidden?'显示桌面伙伴':'隐藏桌面伙伴';$('hideDesktop').setAttribute('aria-label',$('hideDesktop').textContent);$('dndToggle').textContent=state.settings.dnd?'退出勿扰':'开启勿扰';$('dndToggle').classList.toggle('selected',state.settings.dnd);$('dndToggle').setAttribute('aria-pressed',String(state.settings.dnd));}
async function renderTab(){if(view!=='panel')return;const revision=++renderRevision;document.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('pageTitle').textContent=({chat:'聊一聊',memory:'记忆管理',model:'模型与费用',settings:'伙伴设置'} as any)[tab];$('headerActions').innerHTML=tab==='chat'?'<button id="newChat">新对话</button><button id="chatHistory">聊天历史</button>':'';if(tab==='chat'){$('newChat').onclick=async()=>{if(await act('end-session')){selectedSession='';privateMessages=[];live='';await renderTab();}};$('chatHistory').onclick=()=>void showHistory();await renderChat(revision);}else{const mem=await api.memory();if(revision!==renderRevision)return;if(tab==='memory')renderMemory(mem);if(tab==='model')renderModel(mem);if(tab==='settings')renderSettings(mem);}}
api.on('state',async next=>{const previous=state;state=next;if(!previous)return;applyTheme();if(isSpeech&&previous.settings.bubbleFontSize!==next.settings.bubbleFontSize)reflowBubble();if(isSpeech&&previous.settings.characterId!==next.settings.characterId){clearTimeout(bubbleTimer);bubbleQueue=[];fragment='';$('bubble').textContent='';$('bubble').classList.remove('visible');void act('bubble-visibility',{visible:false});}if(view==='panel'&&previous.settings.dnd!==next.settings.dnd)toast(next.settings.dnd?'已开启勿扰':'已退出勿扰');if(view==='panel'){syncHeader();if(next.tab&&next.tab!==tab){tab=next.tab==='learning'?'chat':next.tab;await renderTab();}else if(previous.sessionId!==next.sessionId||previous.settings.characterId!==next.settings.characterId){selectedSession='';privateMessages=[];await renderTab();}else syncChatTools();}if(view==='quick'&&$('quickSend')){$('quickSend').textContent=next.busy?'停止':'发送';$('quickName').textContent=next.settings.name;}});
api.on('stream',async event=>{
  if(event.type==='start'&&event.kind==='chat'){activeRequest=event.id;privateRequest=event.private;pending=true;live='';fragment='';bubbleQueue=[];clearTimeout(bubbleTimer);if(view==='panel'&&event.private)privateMessages.push({role:'user',content:event.userText});if(isSpeech)$('bubble').classList.remove('visible');if(view==='panel'&&tab==='chat'){history=await api.history(selectedSession||state.sessionId);if(activeRequest===event.id){await drawMessages();if($('send'))$('send').textContent='停止生成';}}}
  if(event.type==='text_delta'&&event.id===activeRequest){live+=event.text;if(isSpeech)queueSentences(event.text);if(view==='panel'&&tab==='chat')await drawMessages();}
  if(event.type==='error')toast(event.text);
  if(event.type==='done'&&event.kind==='chat'&&activeRequest===event.id){pending=false;if(isSpeech)queueSentences('',true);if(view==='panel'){if(privateRequest&&live)privateMessages.push({role:'assistant',content:live});live='';history=await api.history(selectedSession||state.sessionId);if(tab==='chat'&&activeRequest===event.id){await drawMessages();if($('send'))$('send').textContent='发送';}}}
  if(event.type==='proactive'&&view==='panel'){if(!event.saved)privateMessages.push({role:'assistant',content:event.text});history=await api.history(selectedSession||state.sessionId);if(tab==='chat')await drawMessages();}
  if(event.type==='review'&&view==='panel'){reviewQuestion=event.text;syncChatTools();}
  if(event.type==='memory-updated'&&view==='panel'&&tab==='memory')await renderTab();
  if(event.type==='viewer'&&isSpeech&&!state.settings.bubbleRotation){fragment='';bubbleQueue=[];showBubble('详细回复已放在聊天中。');}
});
document.addEventListener('click',event=>{const a=(event.target as HTMLElement).closest('a');if(a){event.preventDefault();void act('external-link',a.getAttribute('href'));}});
document.addEventListener('mouseover',event=>{const helpElement=(event.target as HTMLElement).closest('.help');if(!helpElement)return;const mark=helpElement.querySelector('.helpMark')!,tip=helpElement.querySelector<HTMLElement>('.tooltip')!;const rect=mark.getBoundingClientRect();tip.style.position='fixed';tip.style.bottom='auto';tip.style.transform='none';const width=tip.getBoundingClientRect().width,height=tip.getBoundingClientRect().height;tip.style.left=Math.max(8,Math.min(rect.left-width/2,innerWidth-width-8))+'px';tip.style.top=(rect.top-height-9>=8?rect.top-height-9:rect.bottom+9)+'px';});
void (async()=>{state=await api.state();applyTheme();if(view==='pet')createPet();else if(isSpeech){app.innerHTML='<div id="bubble" class="bubble"></div>';$('bubble').onclick=()=>void act('open','chat');api.on('pointer',point=>{const el=$('bubble'),r=el.getBoundingClientRect();api.hit(el.classList.contains('visible')&&point.x>=r.left&&point.x<=r.right&&point.y>=r.top&&point.y<=r.bottom);});api.on('bubble',event=>{if(event.text){fragment='';bubbleQueue=[];showBubble(event.text);}});}else if(view==='quick')createQuick();else if(view==='restore'){app.innerHTML='<button id="restorePet" class="restoreButton" aria-label="显示桌面伙伴" title="显示桌面伙伴"><img id="restoreAvatar" alt="伙伴头像"><span class="restoreQuiet" aria-hidden="true">☾</span></button>';$('restorePet').onclick=()=>void act('show');syncCompanionStatus();}else{shell();await renderTab();if(!state.settings.onboardingSeen)showGuide();}})();
